[package]
name = "thunder-watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.28.1"
chrono = "0.4.19"
lightning = "0.0.109"
rand = "0.8.5"
